#spring.data.mongodb.host = localhost
#spring.data.mongodb.port = 27017


#spring.data.mongodb.uri = mongodb+srv://richay2411_db_user:Richa24@cluster0.hcqh6k4.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database = journaldb
#spring.data.mongodb.auto-index-creation=true
#
#server.port = 8080
#server.servlet.context-path = /journal
#spring.security.user.name=richa
#spring.security.user.password=richa123
#spring.data.mongodb.username = myjournaluser
#spring.data.mongodb.password = mypassword